# syntax=docker/dockerfile:latest
# escape=`
# check=error=true

FROM python:3.12-slim

LABEL maintainer="github.com/abombalemba"

WORKDIR /src

COPY . .

RUN python -m venv venv
RUN source venv/bin/activate && pip install -r requirements.txt

EXPOSE 5050

CMD [
    "venv/bin/python3", "server.py"
]

RUN deactivate
